# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBase-Auth-Lab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBase-Auth-Lab

  target 'FireBase-Auth-LabTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
